---
server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amrutaDesai/springBootCloudConfigServer
          search-paths: 'station*'
          repos:
            perf:
              pattern:
               - '*/perf'
              uri: https://github.com/amrutaDesai/springCloudConfigServerPerformance
              search-paths: 'station*'
        encrypt:
          enabled: false

security:
  basic:
    enabled: true
  user:
    name: rabbit
    password: rabbit

